title: Ruocheng Dong,MS # your name (or website title) here
logo: "/images/logo.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D candidate @ University of Wisconsin-Madison
  
  Genetic Epidemilogy

  Minor: Bioinformatics and Statistical Omics Analysis
  <br><br>
  MS in Biostatistics @ Georgetown University
  <br><br>
 [Email](mailto:ruocheng.dong@wisc.edu?subject=[GitHub]%20Source%20Han%20Sans)
   
theme: jekyll-theme-minimal
