title: Ruocheng Dong # your name (or website title) here
logo: "/images/logo.jfif?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Ph.D candidate @ UW-Madison
  Genetic Epidemilogy
  <br><br>
  Second description 
  <br><br>
  Email:<ruocheng.dong@wisc.edu>
  <a href="https://www.linkedin.com/in/ruocheng-dong-20808ba9/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
